name: Quality Checks

on:
  workflow_call:

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true

      - name: "Setup PDM"
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          cache: true
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: pdm install --frozen-lockfile --group dev

      - name: Build
        run: pdm build

      - name: Publish
        run: pdm publish
