name: Quality Checks

on:
  workflow_call:

jobs:
  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: true

      - name: "Setup PDM"
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          cache: true
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: pdm install --frozen-lockfile --group dev

      - name: Build
        run: pdm build

      - name: Publish
        run: pdm publish