name: Quality Checks

on:
  workflow_call:

jobs:
  check-license-header:
    name: License Header Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
      - name: Setup licensor
        uses: nicebots-xyz/licensor/.github/actions/setup-licensor@9b1b5450cb3d59e3f010a8203d696173aba3b564
        with:
          version: v0.0.5
      - name: Check Header Compliance
        run: licensor check "." --ignore ".*" --ignore ".*/**" --ignore "src/dismoji/raw/**"
  
  tests:
    name: Tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        include:
          - python-version: "3.10"
            name: "Python 3.10"
          - python-version: "3.11"
            name: "Python 3.11"
          - python-version: "3.12"
            name: "Python 3.12"
          - python-version: "3.13"
            name: "Python 3.13"
          - python-version: "3.14"
            name: "Python 3.14"
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          submodules: true

      - name: "Set up Python"
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: "Setup PDM"
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          cache: true
          python-version: ${{ matrix.python-version }}
  
      - name: Install dependencies
        run: pdm install --frozen-lockfile --group dev

      - name: Run tests
        run: pdm run test

  quality:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        check: [format, lint, basedpyright]
        include:
          - check: format
            name: "Format Check"
            command: "pdm run format"
          - check: lint
            name: "Lint Check"
            command: "pdm run lint"
          - check: basedpyright
            name: "Type Check"
            command: "pdm run typecheck"

    name: ${{ matrix.name }}

    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: "Setup PDM"
        uses: pdm-project/setup-pdm@94a823180e06fcde4ad29308721954a521c96ed0 # v4
        with:
          cache: true
          python-version-file: "pyproject.toml"

      - name: Install dependencies
        run: pdm install --frozen-lockfile --group dev

      - name: ${{ matrix.name }}
        run: ${{ matrix.command }}